### ISSUE TITLE
Low SNR in I/O raw file

### ISSUE THREAD

**Issue by andimik** [Opendigitalradio/ODR-DabMod#13]
I used the ini file from https://www.welle.io/devices/rawfile to create an I/O raw file from an ETI.

But I get a file with a very small SNR (screenshots taken from qt-dab and welle.io)

![grafik](https://cloud.githubusercontent.com/assets/24510556/24648669/a32cd750-1924-11e7-8cd3-836e56f3fe8d.png)

![unbenannt](https://cloud.githubusercontent.com/assets/24510556/24648794/14ab401a-1925-11e7-96fd-cf701441354c.png)

How can I improve it?
(Albert himself recommended to open an issue here)

**Comment by rashuk** [comment]
Hello,

It probably has something to do with welle.io expecting only unsigned 8-bit
(0-255) interleaved samples, not the signed 8-bit samples generated by
odr-dabmod.

I'd imagine you're losing a lot of dynamic range as it is seems to be able
to use the positive samples (0-127) but everything else (-1 to -128) will
be out of range.

That is where your SNR has gone! :-)

Best regards,

Rash.

**Comment by rashuk** [comment]
Actually, not quite...

You've only lost 1-bit of resolution because the highest integer (127) can
be represented with 7-bits, so you've only lost 6dB of theoretical dynamic
range. I can only imagine that somehow the 'bad' negative numbers become
the noise floor, leaving you with only ~6dB SNR. That's pretty close to
what we can see on your qt-dab screenshot. Somebody clever will be able to
elaborate on this no doubt!

R.

**Comment by andimik** [comment]
Could you upload a screenshot how it should look like?

In the meanwhile I'll try to convert it with sox

**Comment by rashuk** [comment]
Hello,

I don't have the same tools installed I'm afraid, and I don't keep IQ files
around for long!

The below is from RF, not baseband, and with a higher resolution (14-bit)
DAC. With 8-bit samples you will see no more than the the 48 dB (8-bits*6)
between the flat top and the noise floor. Expect a few dB less. Ignore the
spurious spike in the picture and the uneven noise.

If you wanted you could open it in a gnu radio flowgraph (not forgetting to
tell it the samples are signed integers and throttle them to 2048k
sampling, then pass them to an fft display.

That should work but I've never had a reason to do it.

R.

On 4 Apr 2017 15:49, "andimik" <notifications@github.com> wrote:

Could you upload a screenshot how it should look like?

In the meanwhile I'll try to convert it with sox

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/Opendigitalradio/ODR-DabMod/issues/13#issuecomment-291524016>,
or mute the thread

**Comment by andimik** [comment]
Yeah, your hint was the solution.

If someone else wants to try: The command is

`sox -e signed-integer -r 240000 -t raw -c 2 -b 8 DabMod.iq -e unsigned-integer -t raw -c 2 -b 8 -r 240000 DabMod_new.iq
`
(sox has to be installed of course)

![grafik](https://cloud.githubusercontent.com/assets/24510556/24674144/beac4500-197a-11e7-82ed-bb35c3ca2a42.png)

I will tell Albrecht to include this ;-)
