### ISSUE TITLE
Poor signal with activated TII 

### ISSUE THREAD

**Issue by andimik** [Opendigitalradio/ODR-DabMod#24]
I tried to activate TII but then my Sticks and radios either don't lock at all or get a very poor signal (Microspot 4 squares instead of 16).

Seems the null symbol causes a gain issue on the receiver side.

**Comment by andimik** [comment]
The latest from the next. I've posted the version in the (closed) issue about edi.

**Comment by andimik** [comment]
ODR-DabMod version v2.0.0-26-g9ef3824, compiled at May 13 2018

**Comment by andimik** [comment]
Digital gain is 0.8

**Comment by mpbraendli** [comment]
Ok. I also used `next` to do a test, enabling/disabling TII with the remote-control. I wasn't able to see any effect on my receivers :-/
Can you post your .ini file in a github gist or on https://paste.ubuntu.com/ and send me a link?

**Comment by andimik** [comment]
Well, now I remember. When I started the issue I still had Ubuntu 16.04. Some days ago I re-installed a clean 18.04 Kubuntu. And tested it again right now. Seems we can close now.

**Comment by rashuk** [comment]
Hello,

I'm surprised that this can work because you are using the native sampling
rate which does not push the image frequencies far enough into the
stop-band of the 1.75 MHz monolithic filter inside the transceiver chip.
Trust me - it looked truly awful on a spectrum analyser!.;-D

If you have sufficient cpu resources, try to operate odr-dabmod and
hackrf_transfer at a higher sampling rate, ideally at least 4.096M. It will
clean up your signal a lot and the image won't be there to clobber
reception. Disable the FIR filter if you have too because it would still
much better than the close-in image interference.

Hope this is useful!

R.

**Comment by andimik** [comment]
Ok thanks, I'll try that instead.

**Comment by mpbraendli** [comment]
If you read from a file, better specify the filename in the `.ini` over using `more`. `cat` would be more appropriate (pun not intended) because `more` is a pager, it could actually mess with file contents.
Thanks for reporting issues, even if this was (luckily) a false positive!

**Comment by andimik** [comment]
Ok, thanks.

I also had to change `rate=2048000` in the ini-file to 4096k.

**Comment by andimik** [comment]
Well, I don't see a difference between 4M and 2M beside of higher traffic and CPU usage. Signal is the same. Both work here.

**Comment by mpbraendli** [comment]
How do you measure your signal? Do you have a spectrum analyser?

**Comment by andimik** [comment]
Qt-dab

**Comment by mpbraendli** [comment]
qt-dab doesn't show a wide enough bandwidth, so you won't see the effect Rash is talking about.

**Comment by andimik** [comment]
4096k and CPU usage 40%
![grafik](https://user-images.githubusercontent.com/24510556/40159256-ad7d5282-59a8-11e8-8335-7c2d9f4816c1.png)
2048k and CPU usage 35%
![grafik](https://user-images.githubusercontent.com/24510556/40159269-c38e3c30-59a8-11e8-9a5a-7b5bd2f015fa.png)

For testing (and helping FMSCAN to be updated with CSV files from Andreas Gsinn's Player) this is absolutely ok.
