### ISSUE TITLE
reduced footprint for Docker (separate build without libuhd-dev)

### ISSUE THREAD

**Issue by DAMEK86** [Opendigitalradio/ODR-DabMod#34]
in case of using DabMod for signal generation, it would be nice to remove libuhd-dev dependency.
we like to include your tools in a docker container and trigger it from ssh

in case of libuhd-dev, the debian:buster-slim image (68,9MB) grows up to 1,7 GB.

an minimal build with reduced dependencies would be very nice.
what do you think about? is it an option four you?

kind regards

**Comment by rashuk** [comment]
Hello,


I am probably not the right person to answer this, but surely you don't
need all of that if you compile it without a uhd output? You can disable it
with configure.

That's recommended unless using a USRP as UHD has a habit of printing stuff
to stdout, which can cause trouble if pipelining into hackrf_transfer or
fl2k etc...

Best regards,

Rash.

**Comment by barczynsky** [comment]
I'm pretty sure you can build dabmod without a trace of UHD drivers in your system, since I was the first to turn this around, see the past [changes](https://github.com/Opendigitalradio/ODR-DabMod/pull/1).

I believe what you are looking for is the **--disable-output-uhd** flag, or so it was called. Then it's just up o the method you are using to install build dependencies - in any case, just avoid installing libuhd(-dev) unless necessary (or you need to use it with the USRP or other compatible devices).

That was possible back then when I was using dabmod extensively, and I suppose that scenario is still valid and didn't change much since then. Figured all things will end up in a container of some sort anyway.

Cheers,

-- Emil

**Comment by mpbraendli** [comment]
Please re-open the issue if this is still an issue
